version: '3'
services:
  flask:
    
    build: ./
    
    container_name: url-shortener
    
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True                   
    
    restart: on-failure

    volumes:
      - .:/app
    
    ports:
      - "5000:5000"

    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app